library(devtools)
library(roxygen2)
library(available)
library(usethis)
devtools::load_all("~/Documents/Karnovsky_lab/DNEAdev/", reset = TRUE, recompile = TRUE)
#devtools::create('DNEAdev')
available('DNEA')

#add packages
usethis::use_mit_license('DNEADEV')
usethis::use_description()
usethis:: use_mit_license()
usethis::use_package("Matrix")
# usethis::use_package("corpcor")
usethis::use_package("dplyr")
# usethis::use_package("furrr")
usethis::use_package("gdata")
usethis::use_package("glasso")
# usethis::use_package("glmnet")
usethis::use_package("igraph")
usethis::use_package("janitor")
usethis::use_package("methods")
usethis::use_package("stats")
# usethis::use_package("pbapply")
usethis::use_package("stringr")
# usethis::use_package("zoo")
usethis::use_package("netgsa")
usethis::use_package("BiocParallel")
usethis::use_package("autoimage")
usethis::use_package("utils")
# usethis::use_package("future")
usethis::use_package()

#add data
usethis::use_data(TEDDY, overwrite = TRUE)
usethis::use_data(group_labels, overwrite = TRUE)
usethis::use_data(TEDDYresults, overwrite = TRUE)
usethis::use_data(T1Dmeta)

#add to .Rbuildignore
use_build_ignore("~/Documents/Karnovsky_lab/DNEAdev/dev_files/parallelTest.R", escape = TRUE)
use_build_ignore("~/Documents/Karnovsky_lab/DNEAdev/dev_files/TEDDYplasmaIA.csv", escape = TRUE)
use_build_ignore("~/Documents/Karnovsky_lab/DNEAdev/dev_files/workflow.R", escape = TRUE)
use_build_ignore("~/Documents/Karnovsky_lab/DNEAdev/dev_files/Dev.R", escape = TRUE)
use_build_ignore("~/Documents/Karnovsky_lab/DNEAdev/.gitignore", escape = TRUE)
use_build_ignore("~/Documents/Karnovsky_lab/DNEAdev/dev_files/DNEAdevTesting.R", escape = TRUE)

#add tests
usethis::use_testthat()

devtools::document()
devtools::build_manual()
devtools::check()
devtools::build()
