library(devtools)
library(roxygen2)
library(available)
library(usethis)
devtools::load_all("~/Documents/Karnovsky_lab/DNEAdev/", reset = TRUE, recompile = TRUE)
#devtools::create('DNEAdev')
available('DNEA')

usethis::use_mit_license('DNEADEV')
usethis::use_description()
usethis:: use_mit_license()
usethis::use_package("Matrix")
usethis::use_package("corpcor")
usethis::use_package("dplyr")
usethis::use_package("furrr")
usethis::use_package("gdata")
usethis::use_package("glasso")
usethis::use_package("glmnet")
usethis::use_package("igraph")
usethis::use_package("janitor")
usethis::use_package("methods")
usethis::use_package("pbapply")
usethis::use_package("stringr")
usethis::use_package("zoo")
usethis::use_package("netgsa")
usethis::use_package("BiocParallel")
usethis::use_package("future")

devtools::document()
devtools::check()
devtools::build()
